# Generated by Django 5.0.3 on 2024-05-07 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_place', models.CharField(max_length=100)),
                ('employee_mobile_number', models.CharField(max_length=12)),
                ('employee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_app.category_model')),
            ],
        ),
    ]
